name: Atlas Protocol CI
on: [push, pull_request]

jobs:
  forge-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Check Formatting
        run: cd contracts && forge fmt --check
      - name: Build Contracts
        run: cd contracts && forge build
      - name: Run Tests
        run: cd contracts && forge test -vvv
